# Loading data from file

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [5]:
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [6]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=200)

C:\Anaconda3\lib\site-packages\keras\optimizer_v2\gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/200
1/1 [==============================] - 0s 275ms/step - loss: 8977.6064
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 3365.5188
Epoch 3/200
1/1 [==============================] - 0s 2ms/step - loss: 1290.5376
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 523.3232
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 239.6265
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 134.6991
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 95.8680
Epoch 8/200
1/1 [==============================] - 0s 4ms/step - loss: 81.4747
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 76.1166
Epoch 10/200
1/1 [==============================] - 0s 3ms/step - loss: 74.0991
Epoch 11/200
1/1 [==============================] - 0s 4ms/step - loss: 73.3167
Epoch 12/200
1/1 [==============================] - 0s 2ms/step - loss: 72.9911
Epoch 13/200
1/1 [====================

1/1 [==============================] - 0s 2ms/step - loss: 67.7826
Epoch 104/200
1/1 [==============================] - 0s 3ms/step - loss: 67.7293
Epoch 105/200
1/1 [==============================] - 0s 2ms/step - loss: 67.6761
Epoch 106/200
1/1 [==============================] - 0s 3ms/step - loss: 67.6229
Epoch 107/200
1/1 [==============================] - 0s 3ms/step - loss: 67.5697
Epoch 108/200
1/1 [==============================] - 0s 4ms/step - loss: 67.5165
Epoch 109/200
1/1 [==============================] - 0s 2ms/step - loss: 67.4635
Epoch 110/200
1/1 [==============================] - 0s 2ms/step - loss: 67.4105
Epoch 111/200
1/1 [==============================] - 0s 3ms/step - loss: 67.3575
Epoch 112/200
1/1 [==============================] - 0s 2ms/step - loss: 67.3045
Epoch 113/200
1/1 [==============================] - 0s 3ms/step - loss: 67.2517
Epoch 114/200
1/1 [==============================] - 0s 2ms/step - loss: 67.1989
Epoch 115/200
1/1 [=======================

In [7]:
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[163.56192]]
Other scores will be  [[127.184105]
 [199.7128  ]]
