# Deep leaning basic

## 1. 데이터 생성

In [1]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.7.0'

In [2]:
x_data = np.array([2, 4, 6, 8, 10,
                   12, 14, 16, 18, 20]).astype('float32')

y_data = np.array([0, 0, 0, 0, 0, # train data
                   0, 1, 1, 1, 1]).astype('float32')

## 2. 모델 구축

In [3]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(8, input_shape=(1,), 
                            # 8 : 은닉층 노드 개수  .  1 : 입력층 노드 개수
                                activation='sigmoid'))


model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
                            # 1: 출력층 노드 개수

- Logistic Regression 과 Deep Learning의 차이는 은닉층 유무!
- 은닉층 노드의 개수는 개발자가 정해서 최적을 알아내야하는 하이퍼 파라미터 (Hyperparameter)임

In [4]:
model.compile(tf.keras.optimizers.SGD(learning_rate=0.1),
              loss='binary_crossentropy', metrics=['accuracy'])
                # loss : 손실함수  ,  metrics  :  측정지표

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 16        
                                                                 
 dense_1 (Dense)             (None, 1)                 9         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


Param #  : 최적의 값으로 학습되는 가중치와 바이어스 개수 \
16 : 가중치 개수(1x8) + 바이어스 개수(8) \
9 : 가중치 개수(8x1) + 바이어스 개수

In [5]:
hist = model.fit(x_data, y_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 335ms/step - loss: 0.7032 - accuracy: 0.6000
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6826 - accuracy: 0.6000
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6718 - accuracy: 0.6000
Epoch 4/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6657 - accuracy: 0.6000
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6617 - accuracy: 0.6000
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6588 - accuracy: 0.6000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6565 - accuracy: 0.6000
Epoch 8/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6545 - accuracy: 0.6000
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6526 - accuracy: 0.6000
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6507 - accuracy: 0.6000
Epoch 11/500
1/1 [=========

1/1 [==============================] - 0s 3ms/step - loss: 0.5638 - accuracy: 0.7000
Epoch 85/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5630 - accuracy: 0.7000
Epoch 86/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5622 - accuracy: 0.7000
Epoch 87/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5614 - accuracy: 0.7000
Epoch 88/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5607 - accuracy: 0.7000
Epoch 89/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5599 - accuracy: 0.7000
Epoch 90/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5591 - accuracy: 0.7000
Epoch 91/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5583 - accuracy: 0.7000
Epoch 92/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5576 - accuracy: 0.7000
Epoch 93/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5568 - accuracy: 0.7000
Epoch 94/500
1/1 [===============

1/1 [==============================] - 0s 3ms/step - loss: 0.4966 - accuracy: 0.9000
Epoch 168/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4957 - accuracy: 0.9000
Epoch 169/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4948 - accuracy: 0.9000
Epoch 170/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4940 - accuracy: 0.9000
Epoch 171/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4931 - accuracy: 0.9000
Epoch 172/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4922 - accuracy: 0.9000
Epoch 173/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4914 - accuracy: 0.9000
Epoch 174/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4905 - accuracy: 0.9000
Epoch 175/500
1/1 [==============================] - 0s 2ms/step - loss: 0.4896 - accuracy: 0.9000
Epoch 176/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4888 - accuracy: 0.9000
Epoch 177/500
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 0.4312 - accuracy: 1.0000
Epoch 250/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4304 - accuracy: 1.0000
Epoch 251/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4297 - accuracy: 1.0000
Epoch 252/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4290 - accuracy: 1.0000
Epoch 253/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4282 - accuracy: 1.0000
Epoch 254/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4275 - accuracy: 1.0000
Epoch 255/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4267 - accuracy: 1.0000
Epoch 256/500
1/1 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 1.0000
Epoch 257/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4253 - accuracy: 1.0000
Epoch 258/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4245 - accuracy: 1.0000
Epoch 259/500
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 0.3741 - accuracy: 1.0000
Epoch 332/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3734 - accuracy: 1.0000
Epoch 333/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 1.0000
Epoch 334/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3721 - accuracy: 1.0000
Epoch 335/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3715 - accuracy: 1.0000
Epoch 336/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3708 - accuracy: 1.0000
Epoch 337/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3702 - accuracy: 1.0000
Epoch 338/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3696 - accuracy: 1.0000
Epoch 339/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3689 - accuracy: 1.0000
Epoch 340/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3683 - accuracy: 1.0000
Epoch 341/500
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 0.3255 - accuracy: 1.0000
Epoch 414/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3250 - accuracy: 1.0000
Epoch 415/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3244 - accuracy: 1.0000
Epoch 416/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3239 - accuracy: 1.0000
Epoch 417/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3234 - accuracy: 1.0000
Epoch 418/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3228 - accuracy: 1.0000
Epoch 419/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3223 - accuracy: 1.0000
Epoch 420/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3218 - accuracy: 1.0000
Epoch 421/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3212 - accuracy: 1.0000
Epoch 422/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3207 - accuracy: 1.0000
Epoch 423/500
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 0.2854 - accuracy: 1.0000
Epoch 496/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2850 - accuracy: 1.0000
Epoch 497/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2846 - accuracy: 1.0000
Epoch 498/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2841 - accuracy: 1.0000
Epoch 499/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2837 - accuracy: 1.0000
Epoch 500/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2833 - accuracy: 1.0000


In [10]:
test_data = np.array([0.1, 3.0, 4.5, 
                      11.7, 13.0, 31.0])

sigmoid_value = model.predict(test_data)

logical_value = tf.cast(sigmoid_value > 0.5,
                      dtype=tf.float32)
# sigmoid 함수를 사용하기 떄문에 0.5보다 클 때와 아닐 때를 이용하여
# Binary Classification(이항 분류)

for i in range(len(test_data)):
    print(test_data[i], 
          sigmoid_value[i], 
          logical_value.numpy()[i])

0.1 [0.02539149] [0.]
3.0 [0.04205456] [0.]
4.5 [0.06588423] [0.]
11.7 [0.4397349] [0.]
13.0 [0.5280308] [1.]
31.0 [0.88423467] [1.]


In [11]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 8) dtype=float32, numpy=
 array([[ 0.85381925,  0.76638854, -0.14008908, -0.17686026, -0.16613762,
          0.9317347 ,  0.16166882,  0.15699984]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(8,) dtype=float32, numpy=
 array([ 0.01805657,  0.08574659,  0.38918915,  1.2193531 ,  0.9993422 ,
         0.06444186, -0.9033264 , -0.79989487], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(8, 1) dtype=float32, numpy=
 array([[-0.15519457],
        [-0.3668429 ],
        [-1.1545527 ],
        [-2.2840412 ],
        [-2.0005388 ],
        [-0.49299085],
        [ 1.780172  ],
        [ 1.6518953 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-0.24282739], dtype=float32)>]