# Softmax classifier

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [3]:
nb_classes = 7  # 0 ~ 6

In [4]:
# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
# Y값을 one_hot으로 바꿈
print("one_hot:", y_one_hot)

one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [5]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_one_hot, epochs=200)

C:\Anaconda3\lib\site-packages\keras\optimizer_v2\gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 119       
                                                                 
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
4/4 [==============================] - 0s 1ms/step - loss: 2.1538 - accuracy: 0.1485
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 1.7281 - accuracy: 0.3762
Epoch 3/200
4/4 [==============================] - 0s 2ms/step - loss: 1.4527 - accuracy: 0.4059
Epoch 4/200
4/4 [==============================] - 0s 2ms/step - loss: 1.2894 - accuracy: 0.4950
Epoch 5/200
4/4 [==============================] - 0s 4ms/step - loss: 1.1542 - accuracy: 0.5545
Epoch 6/200
4/4 [==============================] - 0s 4ms/step - loss: 1.0592 - accuracy: 0.6733
Epoc

4/4 [==============================] - 0s 2ms/step - loss: 0.2298 - accuracy: 0.9802
Epoch 80/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2316 - accuracy: 0.9802
Epoch 81/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2266 - accuracy: 0.9802
Epoch 82/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2238 - accuracy: 0.9802
Epoch 83/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2213 - accuracy: 0.9802
Epoch 84/200
4/4 [==============================] - 0s 4ms/step - loss: 0.2212 - accuracy: 0.9802
Epoch 85/200
4/4 [==============================] - 0s 4ms/step - loss: 0.2184 - accuracy: 0.9802
Epoch 86/200
4/4 [==============================] - 0s 4ms/step - loss: 0.2174 - accuracy: 0.9802
Epoch 87/200
4/4 [==============================] - 0s 3ms/step - loss: 0.2166 - accuracy: 0.9802
Epoch 88/200
4/4 [==============================] - 0s 3ms/step - loss: 0.2130 - accuracy: 0.9802
Epoch 89/200
4/4 [===============

4/4 [==============================] - 0s 2ms/step - loss: 0.1377 - accuracy: 0.9802
Epoch 163/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1384 - accuracy: 0.9802
Epoch 164/200
4/4 [==============================] - 0s 2ms/step - loss: 0.1368 - accuracy: 0.9802
Epoch 165/200
4/4 [==============================] - 0s 2ms/step - loss: 0.1356 - accuracy: 0.9802
Epoch 166/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1364 - accuracy: 0.9802
Epoch 167/200
4/4 [==============================] - 0s 1ms/step - loss: 0.1355 - accuracy: 0.9802
Epoch 168/200
4/4 [==============================] - 0s 2ms/step - loss: 0.1359 - accuracy: 0.9802
Epoch 169/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1334 - accuracy: 0.9802
Epoch 170/200
4/4 [==============================] - 0s 1ms/step - loss: 0.1333 - accuracy: 0.9802
Epoch 171/200
4/4 [==============================] - 0s 2ms/step - loss: 0.1338 - accuracy: 0.9802
Epoch 172/200
4/4 [=====